#!/bin/sh

# : "${THEPKG_PREFIX=/data/data/com.termux/files/home/0/thepkg/test}"
: "${THEPKG_PREFIX:=./opt}"
: "${THEPKG_DBPATH:=$THEPKG_PREFIX/../var/db/thepkg}"

## config end ##
set -ue

[ -d "$THEPKG_PREFIX" ] || mkdir -pv "$THEPKG_PREFIX"
[ -d "$THEPKG_DBPATH" ] || mkdir -pv "$THEPKG_DBPATH"

log() { printf %s\\n " -> $*"; }
err() { printf %s\\n >&2 " x> $*"; exit ${2-2}; }


main() {



action=${1-"please specify action add/del"}; shift

case $action in
add)
	case ${1-} in
		--name=*) thepkgname=${1#--name=}; shift;;
		*) case $2 in */*@*.tar*) thepkgname=${2##*/}; thepkgname=${thepkgname%%"@"*};; esac
	esac
	: "${1:?"please specify path"}"

	[ ! -e "$THEPKG_DBPATH/${thepkgname:?"missing or empty thepkgname, use --name=THEPKGNAME"}" ] || \
		err "The pkg '$thepkgname' is already installed" $?
	mkdir "$THEPKG_DBPATH/$thepkgname"
	log "Extracting the pkg '$thepkgname'..."
	tar axvf "$1" -k -C "$THEPKG_PREFIX" | sort -r >"$THEPKG_DBPATH/$thepkgname"/manifest

	# arg [ -s "$THEPKG_DBPATH/$thepkgname"/manifest ]
	[ -s "$THEPKG_DBPATH/$thepkgname"/manifest ] || {
		log "Extracding went wrong"
		if
			[ -d "$THEPKG_DBPATH/$thepkgname" ] && \
			command -v YN_confirm >/dev/null 2>&1 && \
			YN_confirm y "Remove the pkg?"
		then
			main del "$thepkgname"
		fi
	}
	# tar -k    don’t replace existing files, treat them as errors
	# test -s   exists and has a size greater than zero
	;;
del)
	thepkgname=${1:?"missing or empty thepkgname"}
	log "Removing the pkg '$thepkgname'..."
	(
		cd "$THEPKG_PREFIX" || exit
		while IFS= read -r file; do
			case $file in
				*/) rmdir "$file" 2>/dev/null||: ;;
				*) rm "$file";;
			esac
		done
	) < "$THEPKG_DBPATH/$thepkgname"/manifest
	rm "$THEPKG_DBPATH/$thepkgname"/manifest
	rmdir "$THEPKG_DBPATH/$thepkgname"
	;;
--help) log "Usage ${0##*/} [--name=THEPKGNAME] <add/del> <file@ver.tar/THEPKGNAME>";;
*) err "use --help";;
esac



}
main "$@"
