#!/bin/sh

# add 20 new lines to idicate the file have build by source (+ keep this comment)




















set -eu

case ${1?specify operation, see --help} in
--help)
	printf %s\\n \
		"Usage: ${0##*/} -<opt> [pkg]..." \
		"       ${0##*/} env [prog] [arg]..." \
		" -P  print supported options" \
		"" \
		"Arch's pacman-like wrapper for thepkg." \
	;
	exit
	;;
-P)
	if [ -t 1 ]; then s=', '; else s='\n'; fi
	printf %s"$s" -S -Q -Qq -Qi -Ql -Qlq -Qo -Qoq
	printf %s\\n -R
	exit
esac


: "${THEPKG_PREFIX:=}"
: "${THEPKG_DBPATH:="$THEPKG_PREFIX/var/db/thepkg"}"


# external vars: `x` `x_input`
# o: changes `i` var
# o: return code
# note: prints err
input_i() {
	read -r i || { # do trim
		case $x in 1) return 1; esac
		case $x_input in 1)
			printf %s\\n >&2 "E: empty input"
			return 1
		esac
	}
	x_input=0
	case $i in -) printf %s\\n >&2 "e: bad input: '-'"; esac
	set -- "$@" -
	# also allow input to use which. (check if this is the bechaviour in pacman, probably not)
}

op_S() {
	case $1 in */*)
		thepkg add "$@" < "$1"
		return
	esac
	thepkg add "$@"
}
op_Q() {
	x_err=0
	x_err() {
		printf %s\\n "$1 \$?: $?"
		x_err=5
	}

	case $# in 0)
		case $op in
			-Q) ls -FA1 -- "$THEPKG_DBPATH" || x_err ls; return $x_err;;
			-Qq) ( cd "$THEPKG_DBPATH" && printf %s\\n * ) || x_err 'cd&&printf'; return $x_err;;
			-Qi|-Ql|-Qlq) set -- "$THEPKG_DBPATH"/*;;
		esac
	esac

	x_missing=0
	while case $# in 0) false; esac; do i=$1
		case $i in -) input_i || return; esac

		case $i in
			*/*) j=$i;;
			*) j=$THEPKG_DBPATH/$i;;
		esac

		if [ -e "$j" ]; then
			case $op in
				-Q) ls -FA1 -d -- "$j" || x_err ls;;
				-Qq) printf %s\\n "$i";;
				-Qi) printf %s\\n "$j:"; ls -FA1 -- "$j" || x_err ls; echo;;
				-Ql) printf %s\\n "$j:"; cat "$j/manifest" || x_err cat; echo;;
				-Qlq) cat "$j/manifest" || x_err cat;;
			esac || { printf %s\\n "\$?: $?"; x_err=5; }
		else
			printf %s\\n "E: pkg not installed: '$i'" >&2
			x_missing=1
		fi

	shift; done
	case $x_missing:$x_err in
		0:0) ;;
		0:*) return $x_err;;
		*:0) return $x_missing;;
		*:*) return 15;; # 15=0b1111=0xf when multiple errors
	esac
}

op_Qq(){ op_Q "$@";}
op_Qi(){ op_Q "$@";}
op_Ql(){ op_Q "$@";}
op_Qlq(){ op_Q "$@";}
op_Qo() {
	case $# in 0) printf %s\\n " x> specify <pkg>"; return 2; esac

	x=0
	cd "$THEPKG_DBPATH" || return

	unset i
	while
		${i+shift};
		case $# in 0) false; esac
	do i=$1
		case $i in -) input_i || return; esac

		case $i in
			*/*) j=$i;;
			*) j=$(which 2>/dev/null "$i") && case $j in */*) ;; *) false; esac;;
		esac || {
			x=1
			printf %s\\n >&2 "E: cant find absolute path for command: '$i'"
			continue
		}
		j=${j#"$THEPKG_PREFIX"}; j=${j#"${THEPKG_PREFIX:+/}"} # note: this will fail if bin from package have been installed in symlink ( for example /bin symlink to /usr/bin )

		case $op in
			-Qo)
				printf %s\\n "$i:" # note: will print before is chekced if any results
				grep -xFe "$j" -- */manifest || {
					x=1
					printf %s\\n >&2 "E: no pkg owns: '$j'"
				}
				echo
				;;
			-Qoq)
				xx=1
				for ii in */manifest; do
					grep -q -xFe "$j" -- "$ii" || continue
					xx=0
					printf %s\\n "${ii%/*}"
				done
				case $xx in 1)
					x=1
					printf %s\\n >&2 "E: no pkg owns: '$j'"
				esac
			;;
		esac
	done
	return "$x"
}
op_Qoq(){ op_Qo "$@";}
op_R() {
	thepkg del "$@"
}

op=$1; shift

case $op in

	# more human input
	install|add) op=-S;;
	remove|del|uninstall) op=-R;;
	query) op=-Q;;

	env)
		case $# in
		0)
			printf %s\\n THEPKG_PREFIX="$THEPKG_PREFIX" THEPKG_DBPATH="$THEPKG_DBPATH"
			;;
		*)
			export THEPKG_PREFIX THEPKG_DBPATH
			"$@"
		esac
		exit
	;;
esac

case $op in
	-S|-Q|-Qq|-Qi|-Ql|-Qlq|-Qo|-Qoq|-R) op_"${op#-}" "$@";;
	*) printf %s\\n >&2 " x> unknown opt/arg: '$op'"; exit 2;;
esac
